export const WHATSAPP_GROUP_URL="https://chat.whatsapp.com/Gwg3PzkzxeW2DvsUIsVCaC";
const GROUP_CODE="Gwg3PzkzxeW2DvsUIsVCaC"; const ENCODED_URL=encodeURIComponent(WHATSAPP_GROUP_URL);
function getUA(){return navigator.userAgent||navigator.vendor||""}
function isIOS(ua:string){return /iPad|iPhone|iPod/.test(ua)||(/Macintosh/.test(ua)&&navigator.maxTouchPoints>1)}
const IN_APP_PATTERN=/Instagram|FBAN|FBAV|FB_IAB|FB4A|FBMD|FBIOS|MessengerForiOS|Orca-Android|BytedanceWebview|musical_ly|musically|Snapchat|LinkedInApp|Pinterest|Twitter|X11|Line\/|KAKAOTALK|DaumApps/i;
export function isInAppBrowser(ua:string=getUA()){if(IN_APP_PATTERN.test(ua))return true;if(/Android/i.test(ua)&&/;\s*wv\)/.test(ua))return true;if(isIOS(ua)&&!/Safari/i.test(ua))return true;return false}
type Attempt={go:()=>void;wait:number};
function runAttempts(attempts:Attempt[],onStuck:()=>void){let left=false;const markLeft=()=>{if(document.hidden)left=true};document.addEventListener("visibilitychange",markLeft);window.addEventListener("pagehide",()=>{left=true});window.addEventListener("blur",()=>{left=true});const step=(index:number)=>{if(left||document.hidden){cleanup();return}if(index>=attempts.length){cleanup();onStuck();return}try{attempts[index].go()}catch{}window.setTimeout(()=>step(index+1),attempts[index].wait)};function cleanup(){document.removeEventListener("visibilitychange",markLeft)}step(0)}
export function openWhatsAppGroup(onStuck:()=>void=()=>{}){const ua=getUA();const android=/Android/i.test(ua);const ios=isIOS(ua);if(!isInAppBrowser(ua)){window.open(WHATSAPP_GROUP_URL,"_blank","noopener,noreferrer");return}const attempts:Attempt[]=[];if(android){attempts.push({go:()=>{window.location.href=`intent://chat.whatsapp.com/${GROUP_CODE}#Intent;scheme=https;package=com.whatsapp;S.browser_fallback_url=${ENCODED_URL};end`},wait:1200});attempts.push({go:()=>{window.location.href=`intent://chat.whatsapp.com/${GROUP_CODE}#Intent;scheme=https;action=android.intent.action.VIEW;category=android.intent.category.BROWSABLE;S.browser_fallback_url=${ENCODED_URL};end`},wait:1500})}else if(ios){attempts.push({go:()=>{window.location.href=`x-safari-${WHATSAPP_GROUP_URL}`},wait:1200});attempts.push({go:()=>{window.location.href=`googlechrome://${WHATSAPP_GROUP_URL.replace(/^https?:\/\//,"")}`},wait:1200})}attempts.push({go:()=>window.open(WHATSAPP_GROUP_URL,"_blank","noopener,noreferrer"),wait:1500});attempts.push({go:()=>{window.location.href=WHATSAPP_GROUP_URL},wait:1800});runAttempts(attempts,onStuck)}
